#!/usr/bin/env python
import sys,os,time,socket,random,getpass


opts=sys.argv
augustus_bin=os.popen("which augustus").readlines()
if len(augustus_bin)==0:
    print("can not find augustus in PATH")
    exit(-1)
augustus_bin=augustus_bin[0].strip()
try:
    host=opts[opts.index("-host") +1]
except ValueError:
    print("".join(os.popen(augustus_bin+" "+" ".join(sys.argv[1:])).readlines()).strip())
    exit(0)
	
print("".join(os.popen("ssh "+host+" -C "+augustus_bin+" "+" ".join(sys.argv[1:-2])).readlines()).strip())
exit(0)
